# Generated by Django 5.1.2 on 2024-12-30 07:15

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='college',
            name='logo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='logos'),
        ),
    ]
