# Generated by Django 5.1.2 on 2024-12-30 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_college_image_alter_college_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='college',
            name='logo',
            field=models.ImageField(upload_to='logos'),
        ),
    ]
