# Generated by Django 5.1.2 on 2025-01-02 10:32

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_college_image_alter_college_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='images'),
        ),
        migrations.AlterField(
            model_name='college',
            name='logo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='logos'),
        ),
    ]
