# Generated by Django 5.1.2 on 2025-02-12 05:56

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_college_image_alter_college_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='college_courses',
            field=models.ManyToManyField(blank=True, related_name='courses', to='api.course'),
        ),
        migrations.AlterField(
            model_name='college',
            name='college_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='college_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='college_pincode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.location', to_field='pincode'),
        ),
        migrations.AlterField(
            model_name='college',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='images'),
        ),
        migrations.AlterField(
            model_name='college',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='logos'),
        ),
        migrations.AlterField(
            model_name='college',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
