# Generated by Django 5.1.2 on 2025-02-12 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_college_college_courses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='image',
            field=models.FileField(null=True, upload_to='images_college'),
        ),
        migrations.AlterField(
            model_name='college',
            name='logo',
            field=models.FileField(null=True, upload_to='logo'),
        ),
    ]
