# Generated by Django 5.1.2 on 2025-02-12 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_college_image_alter_college_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='college_courses',
        ),
        migrations.AddField(
            model_name='college',
            name='college_courses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.course'),
        ),
    ]
