# Generated by Django 5.1.2 on 2025-02-12 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_college_college_courses_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='college_courses',
        ),
        migrations.AddField(
            model_name='college',
            name='college_courses',
            field=models.ManyToManyField(blank=True, null=True, to='api.course'),
        ),
    ]
